version: "3.7"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: blockscout_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  blockscout:
    image: blockscout/blockscout:latest
    depends_on:
      - postgres
    ports:
      - "4000:4000"  # Web UI -> http://localhost:4000
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545
      NETWORK: Anvil
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/blockscout_dev
      SECRET_KEY_BASE: devsecret
    restart: unless-stopped

volumes:
  pgdata:

